# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Miclle Zheng
email: miclle.zheng@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Miclle's web site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://miclle.me" # the base hostname & protocol for your site
twitter_username: miclle
github_username:  miclle

# Build settings
markdown: kramdown

permalink: /:title/

gems: [jekyll-paginate]

paginate: 10

paginate_path: "/pages/:num/"